---
title: "movie-rating-analysis"
author: "Moch. Iqbal Az-Zahir"
date: "2026-04-30"
output: pdf_document
---

```{r}
library(readr)

data <- read_csv("C:/Users/USER/Downloads/archive (6)/top10K-TMDB-movies.csv")

head(data)
```

```{r}
str(data)
```

```{r}
sum(is.na(data))
```

```{r}
data <- na.omit(data)
```

```{r}
library(ggplot2)

ggplot(data, aes(x = vote_average)) + geom_histogram(bins=20) + theme_light()
```

```{r}
ggplot(data, aes(x = popularity, y = vote_average)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm") +
  theme_minimal()
```

```{r}
mean(data$vote_average)
```

```{r}
model <- lm(vote_average ~ popularity, data = data)
summary(model)
```

```{r}
# X1 vs Y
ggplot(data, aes(x = popularity, y = vote_average)) +
  geom_point()+geom_smooth(method = "lm") 

# X2 vs Y
ggplot(data, aes(x = vote_count, y = vote_average)) +
  geom_point()+geom_smooth(method = "lm") 
```

```{r}
ggplot(data, aes(x = popularity, y = vote_average, color = vote_count)) +
  geom_point()
```

```{r}
ggplot(data, aes(x = popularity, y = vote_average, size = vote_count)) +
  geom_point(alpha = 0.5)
```

```{r}
cor(data[, c("popularity", "vote_count", "vote_average")])
```

```{r}
library(tidyr)
library(dplyr)
```

```{r}
genre_split <- data %>%
  separate_rows(genre, sep = ",")

```

```{r}
genre_dummies <- genre_split %>%
  mutate(value = 1) %>%
  pivot_wider(names_from = genre, values_from = value, values_fill = 0)
```

```{r}
head(genre_dummies)
```

```{r}
genre_analysis <- genre_split %>%
  group_by(genre) %>%
  summarise(avg_rating = mean(vote_average))

genre_analysis
```

```{r}
genre_analysis <- genre_analysis %>%
  arrange(desc(avg_rating))
genre_analysis
```

```{r}
ggplot(genre_analysis, aes(x = reorder(genre, avg_rating), y = avg_rating)) +
  geom_col() +
  coord_flip() +
  labs(
    title = "Average Movie Rating by Genre",
    x = "Genre",
    y = "Average Rating"
  ) +
  theme_minimal()
```
